create table if not exists airports (
    id    bigint PRIMARY KEY,
    code    text,
    site_number    text,
    fac_type    text,
    fac_use    text,
    faa_region    text,
    faa_dist    text,
    city    text,
    county    text,
    state    text,
    full_name    text,
    own_type    text,
    longitude    double,
    latitude    double,
    elevation    integer,
    aero_cht    text,
    cbd_dist    integer,
    cbd_dir    text,
    act_date    text,
    cert    text,
    fed_agree    text,
    cust_intl    text,
    c_ldg_rts    text,
    joint_use    text,
    mil_rts    text,
    cntl_twr    text,
    major    text
);
