# Docker Compose file to support local development of the Fundraising Central scrapers, API and processor.
# See ops/ folder for AWS deployment info.
#
# Uses Compose file version 3 which requires Docker Engine 1.13.0 or higher
# See: https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix
#
# All Fundraising Central services mount the local repository into each container as a volue add /usr/src/app.
# Therefore, changes made locally are reflected inside the containers' file systems.

version: '3.4'

# Use an external volume to persiste local MySQL data between container instances
volumes:
  mysql:    

services:
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: learning
    healthcheck:
      test: "/usr/bin/mysql -hlocalhost -ppassword -uroot -e \"SHOW DATABASES;\""
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
